# Generated by Django 5.2 on 2025-04-24 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_comment_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
    ]
