# Generated by Django 5.2 on 2025-04-24 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_post_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
    ]
